In [ ]:
#Panda stands for panel data
import pandas as pd

print("Current version of your pandas library:",pd.__version__)

In [ ]:
import pandas as pd  # Import the pandas library
import random


# Create a list of student marks
marks = (100, 70, 90, 80)

# Convert the list into a pandas Series
# A Series is a one-dimensional labeled array capable of holding data of any type
student_marks = pd.Series(marks)

# Print the Series to see the marks along with their default index (0, 1, 2, ...)
print(student_marks)
print(student_marks.loc[0])

In [ ]:
name=["Sohel Rana","Meher","Afrin","Queen"]

student_name=pd.Series(name)
print(student_name)

In [ ]:
marks = [100, 70, 90, 80]
name = ["Sohel Rana", "Meher", "Afrin", "Queen"]

student_details = pd.Series(marks, index=name)  
# pd.Series(): creates a one-dimensional labeled array (Series) with optional custom index

print(student_details)

In [ ]:
marks = [100, 70, 90.5, 80]
name = ["Sohel Rana", "Meher", "Afrin", "Queen"]

student_details = pd.Series(marks, index=name)  
# pd.Series(): creates a one-dimensional labeled array (Series) with optional custom index

print(student_details)

print(student_details.loc["Sohel Rana"])  
# .loc[]: access elements by label/index name

student_details.loc["Myself"] = 400 
# .loc[]: can also be used to set a new element with a specific label

print(student_details)

print(student_details.iloc[0])  
# .iloc[]: access elements by integer position

In [ ]:
import pandas as pd

# Data
names = ["Sohel Rana", "Meher", "Afrin", "Queen", "Rahim", "Sara", "Imran", "Nazia", "Tariq", "Rita"]
marks = [100, 70, 90.5, 80, 85, 92, 76, 88, 95, 67]
ages = [20, 19, 21, 22, 20, 19, 23, 21, 22, 20]
cities = ["Dhaka", "Chittagong", "Sylhet", "Dhaka", "Khulna", "Barishal", "Rangpur", "Rajshahi", "Dhaka", "Chittagong"]

# Create Series with marks (labeled by names)
student_marks = pd.Series(marks, index=names)  
# pd.Series(): creates a one-dimensional labeled array

# Create a DataFrame with all details
student_details = pd.DataFrame({
    "Marks": marks,
    "Age": ages,
    "City": cities
}, index=names)  
# pd.DataFrame(): creates a two-dimensional labeled data structure (rows & columns)

# Print examples
print(student_marks)
print(student_details)

In [ ]:
# Data
names = ["Sohel Rana", "Meher", "Afrin", "Queen", "Rahim", "Sara", "Imran", "Nazia", "Tariq", "Rita"]
marks = [100, 70, 90.5, 80, 85, 92, 76, 88, 95, 67]
ages = [20, 19, 21, 22, 20, 19, 23, 21, 22, 20]
cities = ["Dhaka", "Chittagong", "Sylhet", "Dhaka", "Khulna", "Barishal", "Rangpur", "Rajshahi", "Dhaka", "Chittagong"]

brilliant_student=pd.Series(marks,index=names)

print(brilliant_student[brilliant_student>90])

In [ ]:
calories_data = {
    "Day 1": 2200,
    "Day 2": 2100,
    "Day 3": 2500,
    "Day 4": 2300,
    "Day 5": 2400,
    "Day 6": 2000,
    "Day 7": 2600,
    "Day 8": 2250,
    "Day 9": 2350,
    "Day 10": 2450,
    "Day 11": 2150,
    "Day 12": 2550,
    "Day 13": 2400,
    "Day 14": 2300,
    "Day 15": 2500,
    "Day 16": 2600,
    "Day 17": 2100,
    "Day 18": 2000,
    "Day 19": 2700,
    "Day 20": 2300,
    "Day 21": 2450,
    "Day 22": 2550,
    "Day 23": 2200,
    "Day 24": 2100,
    "Day 25": 2350,
    "Day 26": 2500,
    "Day 27": 2400,
    "Day 28": 2600,
    "Day 29": 2300,
    "Day 30": 2200
}
calories_series=pd.Series(calories_data)
#print(calories_series)
print(calories_series.mean())     # average calories
print(calories_series.max())      # highest calorie day
print(calories_series.min())      # lowest calorie day
print(calories_series.head(7))    # first 7 days
print(calories_series.tail(7))    # last 7 days
#print("Finding  the days which I spend more caloires more than 2500:",calories_series)

In [ ]:
# Data
names = ["Sohel Rana", "Meher", "Afrin", "Queen", "Rahim", "Sara", "Imran", "Nazia", "Tariq", "Rita"]
marks = [100, 70, 90.5, 80, 85, 92, 76, 88, 95, 67]
ages = [20, 19, 21, 22, 20, 19, 23, 21, 22, 20]
cities = ["Dhaka", "Chittagong", "Sylhet", "Dhaka", "Khulna", "Barishal", "Rangpur", "Rajshahi", "Dhaka", "Chittagong"]


# Create a DataFrame with all details
student_details = pd.DataFrame({
    "Marks": marks,
    "Age": ages,
    "City": cities
}, index=names)  
print(student_details)

In [ ]:
new_data = student_details[(student_details["City"] == "Dhaka") & (student_details["Marks"] > 80)]
# .loc[] can also be used here, but boolean indexing works fine

print(new_data)
new_data["Job"]=[1,2]

In [ ]:
import pandas as pd

name=["Sohel","Afrin"]
id=[573,570]
department=["CSE","EEE"]

stu_details=pd.DataFrame({
    "ID":id,
    "Department":department},index=name)
print(stu_details)

stu_details["Age"]=[23,18]
print(stu_details)

In [ ]:
data = [
    {"Name": "Sohel", "Marks": 90},
    {"Name": "Meher", "Marks": 80},
    {"Name": "Afrin", "Marks": 95}
]
df = pd.DataFrame(data)
print(df)

In [ ]:
import pandas as pd

# Read CSV file into a DataFrame
df = pd.read_csv("student_dataset.csv")  
# pd.read_csv(): reads a CSV file and creates a DataFrame

# Filter students with high marks in all subjects
bright_students = df[(df["Math"] > 95) & (df["Physics"] > 95) & (df["Chemistry"] > 95)]  
# Boolean indexing with & : selects rows where all conditions are True

# Show first 20 bright students
#print(bright_students.head(20))  
# .head(n): returns first n rows

# Get total number of bright students
#total_bright = len(bright_students)  
# len(): counts the number of rows in the DataFrame
# print("Total bright students:", total_bright)
print(df.loc[8999])

In [ ]:
import pandas as pd
import numpy as np
import random

np.random.seed()

names = [f"Student_ID{i}" for i in range(1, 501)]
ages = np.random.randint(18, 25, size=500)
cities = random.choices(["Dhaka", "Chittagong", "Sylhet", "Khulna", "Barishal", "Rajshahi"], k=500)
math = np.random.randint(40, 100, size=500)
physics = np.random.randint(40, 100, size=500)
chemistry = np.random.randint(40, 100, size=500)
english = np.random.randint(50, 100, size=500)
attendance = np.random.randint(60, 100, size=500)
gender = random.choices(["Male", "Female"], k=500)
study_hours = np.random.randint(1, 10, size=500)

df = pd.DataFrame({
    "Student":names,
    "Age": ages,
    "Gender": gender,
    "City": cities,
    "Math": math,
    "Physics": physics,
    "Chemistry": chemistry,
    "English": english,
    "Attendance": attendance,
    "Study_Hours": study_hours
},index=names)
print(df)

# df["Total"] = df[["Math", "Physics", "Chemistry", "English"]].sum(axis=1)
# df["Average"] = (df["Total"] / 4).round(2)
# df.to_csv("student.csv", index=False)

# # print("✅ Extended dataset created!"
# df.head(20)

In [ ]:
df=pd.read_csv("student.csv")
# df.head(20)

# print(df.info())
# print(df.columns)
# df.columns
# df.info()
print(df.to_string())
# df.to_string

In [1]:
import pandas as pd

df = pd.read_csv("student.csv")  
# pd.read_csv(): reads a CSV file and loads it into a DataFrame

df.head()  
# .head(): displays the first 5 rows of the DataFrame


# -----------------------------
# Selection operations
# -----------------------------

# Row selection
# df.loc[] : selects rows using labels (index names)
# df.iloc[] : selects rows using integer positions
# Example:
# print(df.iloc[0])   # prints first row


# Column selection
# df["ColumnName"] : selects a single column as a Series
# df[["Col1", "Col2"]] : selects multiple columns as a DataFrame
# Example:
# print(df["Average"])


# Reading CSV and setting a specific column as index
# pd.read_csv(..., index_col="ColumnName"):
# loads data and sets the given column as the DataFrame index
# Example:
# df = pd.read_csv("student.csv", index_col="Student_ID")


# .loc with list:
# df.loc[["RowLabel1", "RowLabel2"]] : select multiple rows by label


# .iloc slicing:
# df.iloc[start:end:step] : slice rows by integer index

,Student,Age,Gender,City,Math,Physics,Chemistry,English,Attendance,Study_Hours,Total,Average
0,Student_ID1,20,Male,Rajshahi,85,61,48,91,98,7,285,71.25
1,Student_ID2,21,Female,Rajshahi,72,63,74,62,90,7,271,67.75
2,Student_ID3,20,Female,Rajshahi,83,65,52,87,87,3,287,71.75
3,Student_ID4,20,Male,Sylhet,65,54,87,58,95,7,264,66.00
4,Student_ID5,24,Female,Chittagong,69,99,74,89,84,6,331,82.75

In [ ]:
import pandas as pd

df = pd.read_csv("student.csv")  
# pd.read_csv(): loads CSV data into a DataFrame

# df = df.drop(columns=["Study_Hours"])
# .drop(columns=[]): removes specified columns from the DataFrame

df.head()  
# .head(): displays the first 5 rows


# -----------------------------
# Handle missing data
# -----------------------------

# df = df.dropna(subset=[...])
# .dropna(): removes rows containing missing values in the specified columns


# df = df.fillna({"ColumnName": value})
# .fillna(): replaces missing (NaN) values with the given value


# -----------------------------
# Fix inconsistent values
# -----------------------------

# df["ColumnName"] = df["ColumnName"].replace({"Attribute": "NewValue"})
# .replace(): replaces old values with new values in a column


# df["ColumnName"] = df["ColumnName"].str.lower()
# .str.lower(): converts column text to lowercase


# df["ColumnName"] = df["ColumnName"].astype(bool)
# .astype(): converts column datatype to another datatype


# -----------------------------
# Remove duplicates
# -----------------------------

# df = df.drop_duplicates()
# .drop_duplicates(): removes duplicate rows from the DataFrame

,Student,Age,Gender,City,Math,Physics,Chemistry,English,Attendance,Study_Hours,Total,Average
0,Student_ID1,20,Male,Rajshahi,85,61,48,91,98,7,285,71.25
1,Student_ID2,21,Female,Rajshahi,72,63,74,62,90,7,271,67.75
2,Student_ID3,20,Female,Rajshahi,83,65,52,87,87,3,287,71.75
3,Student_ID4,20,Male,Sylhet,65,54,87,58,95,7,264,66.00
4,Student_ID5,24,Female,Chittagong,69,99,74,89,84,6,331,82.75